---
title: "Scaling Up test for GP approach | Test 1"
author: "Naeem Khoshnevis"
date: "6/8/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r}
library(GPCERF)
```

### Example of run

```{r}

set.seed(129)
sim.data <- generate_synthetic_data(sample_size = 400, gps_spec = 3)


# Estimate GPS function
GPS_m <- train_GPS(cov.mt = as.matrix(sim.data[,-(1:2)]),
                   w.all = as.matrix(sim.data$treat))

# exposure values
w.all = seq(0,20,1)

data.table::setDT(sim.data)

cerf_gp_obj <- estimate_cerf_gp(sim.data,
                                w.all,
                                GPS_m,
                                params = list(alpha = 10^seq(-2,0,length.out = 5),
                                              beta = 10^seq(-2,0,length.out = 5),
                                              g_sigma = c(0.1,1,10),
                                              tune_app = "all"),
                                nthread = 12)



plot(cerf_gp_obj)
```

### Scaling test
